server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    secret: asdf234512*    # 盐  越复杂越好
    pubKeyPath: E:\\JavaProject\\leyou\\tmp\\rsa\\rsarsa.pub
    priKeyPath: E:\\JavaProject\\leyou\\tmp\\rsa\\rsa.pri
    expire: 30   #过期时间  单位：分钟
    cookieName: LY_TOKEN