server:
  port: 10086
spring:
  application:
    name: leyou-registry
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
    fetch-registry: false
    register-with-eureka: false