server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=utf8
    username: root
    password: root
  rabbitmq:
    username: leyou
    password: leyou
    virtual-host: /leyou
    host: 127.0.0.1
  redis:
    host: 192.168.31.174
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.user.pojo